Allow passing of a conan profile to rmake

diff --git a/rmake b/rmake
--- a/rmake
+++ b/rmake
@@ -1,28 +1,29 @@
 #!/bin/sh
 
-# rmake [build_type [build_shared_libs]]
-# default: rmake Debug False
+# rmake [BUILD_TYPE [CONAN_PROFILE [BUILD_SHARED_LIBS]]]
+# default: rmake Debug default False
 # examples:
 # rmake
 # rmake Debug
 # rmake Release
-# rmake Debug True
+# rmake Debug my-profile
+# rmake Release my-profile True
 
-BUILD_TYPE=$1
-if [ "$BUILD_TYPE" = "" ]
-then
-  BUILD_TYPE=Debug
-fi
-
-BUILD_SHARED_LIBS=$2
-if [ "$BUILD_SHARED_LIBS" = "" ]
-then
-  BUILD_SHARED_LIBS=False
-fi
+BUILD_TYPE=${1:-Debug}
+CONAN_PROFILE=${2:-default}
+BUILD_SHARED_LIBS=${3:-False}
 
 if [ $BUILD_TYPE != Debug -a $BUILD_TYPE != Release ]
 then
   echo "Invalid build configuration \"$BUILD_TYPE\". Please specify Debug or Release."
+  exit 1
+fi
+
+all_conan_profiles=$(conan profile list)
+if ! [[ $all_conan_profiles =~ $CONAN_PROFILE ]]
+then
+  echo "Invalid value for CONAN_PROFILE \"$CONAN_PROFILE\". Please specify one of the following:"
+  echo $all_conan_profiles
   exit 1
 fi
 
@@ -35,6 +36,7 @@ fi
 echo "rmake configuration:"
 echo " BUILD_TYPE        $BUILD_TYPE"
 echo " BUILD_SHARED_LIBS $BUILD_SHARED_LIBS"
+echo " CONAN_PROFILE     $CONAN_PROFILE"
 echo
 
 if [ ! -f "./build" ]; then mkdir build 2>/dev/null; fi
@@ -44,8 +46,14 @@ if [ ! -f "./$BUILD_TYPE" ]; then mkdir "./$BUILD_TYPE" 2>/dev/null; fi
 
 cd $BUILD_TYPE
 
-conan install ../../conanfile.py --options "*:shared=$BUILD_SHARED_LIBS"
-cmake ../.. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSKIP_INSTALL_ALL=true -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS
+conan install ../../conanfile.py \
+    --options "*:shared=$BUILD_SHARED_LIBS" \
+    --profile $CONAN_PROFILE \
+    --build outdated
+cmake ../.. -G "Unix Makefiles" \
+    -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
+    -DSKIP_INSTALL_ALL=true \
+    -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS
 # 8 threads available for parallel building
 cmake --build . -- -j8
 if [ $? != 0 ]
@@ -67,7 +75,8 @@ conan create ../.. branch/testing \
   --build outdated \
   --options "*:shared=$BUILD_SHARED_LIBS" \
   --options "BranchIO:source_folder=`pwd`/../.." \
-  --settings build_type=$BUILD_TYPE
+  --settings build_type=$BUILD_TYPE \
+  --profile $CONAN_PROFILE
 if [ $? != 0 ]
 then
   echo 'conan create failed.'
